### ISSUE TITLE
Retrieving configuration items from dot notation nested arrays does not work as expected

### ISSUE THREAD

**Issue by asiral** [illuminatech/config#18]
### What steps will reproduce the problem?
If I set two configuration items like the following:
```
setItems([            'services.example.item1' => [
                'label' => 'Item 1',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ],
            'services.example.item2' => [
                'label' => 'Item 2',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ]
])
```
And then I try to retrieve them like so:
```
Config::get('services.example')
```
Nothing is returned (null).

### What is the expected result?
I should get an array of configuration items, item1 and item2.

### What do you get instead?
I get a null response.

### Additional info
The issue seems to be related to the call to [`isPersistentKey`](https://github.com/illuminatech/config/blob/master/src/PersistentRepository.php#L449) when calling [`get`](https://github.com/illuminatech/config/blob/master/src/PersistentRepository.php#L543)

Additionally, if I call `Config::restore()` beforehand, I am able to get the expected result.

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.4.0
| Laravel Framework Version | 10.13.5
| PHP version               | 8.1.20
| Operating system          | CentOS 7.9

**Comment by drbyte** [comment]
Which storage driver are you using? 
Are you using only built-in features of this package? or are you using customized drivers, caches, etc?
Can you provide code for a very simple application that demonstrates this problem?

**Comment by asiral** [comment]
I am using the Eloquent driver.  And I am using built-in features.

Perhaps an important point to note is I am using the recommendation from [this ticket](https://github.com/illuminatech/config/issues/15).

Here is an example Service Provider:
```
<?php

namespace App\Providers;

use DateInterval;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\ServiceProvider;
use Illuminatech\Config\PersistentRepository;
use Illuminatech\Config\StorageEloquent;
use App\Models\ConfigurationItem;

class TestServiceProvider extends ServiceProvider
{

    protected string $configItemCacheKey = 'application.persistent.config';
    protected int|DateInterval $configItemCacheTtl = 3600 * 24;

    public function boot(): void
    {
        $this->app->extend('config', function ($originConfig) {
            $storage = new StorageEloquent(ConfigurationItem::class);
            $newConfigRepository = (new PersistentRepository($originConfig, $storage))
                ->setCache($this->app->make('cache.store'))
                ->setCacheKey($this->configItemCacheKey)
                ->setCacheTtl($this->configItemCacheTtl);

            // Swap the static instance, or the Config object returned from the Config facade will be different from
            // the Config object in the app container. get_class(app('config')) !== get_class(Config::getFacadeRoot()).
            Config::swap($newConfigRepository);

            return $newConfigRepository;
        });

    }
}
```
Another Service Provider to register the persistent configuration items:
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Config;
use Illuminate\Support\ServiceProvider;

class TestTwoServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $existingItems = Config::getItems()->toArray();
        $items = [
            'services.example.item1' => [
                'label' => 'Item 1',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ],
            'services.example.item2' => [
                'label' => 'Item 2',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ],
        ];
        $newItems = array_merge($existingItems, $items);
        config()->setItems($newItems);
        $existingItems = Config::getItems()->toArray();
        $secondItems = [
            'services.example2.item1' => [
                'label' => 'Item 1 of Example 2',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ]
        ];
        $newItems = array_merge($existingItems, $secondItems);
        config()->setItems($newItems);
        //Config::restore();

    }
}

```
And then here is an example route:
```
Route::get('test', function() {
    $config = Config::get('services.example2');
    ddd($config);
});
```
If you uncomment `Config::restore()`, the expected value is dumped.  Calling `Config::get('services.example')` works.

**Comment by asiral** [comment]
Some additional information.  If the recommendation is to call `Config:restore()`, there are two issues.  The first is that it is not clear to the user, or at least to me, according to the documentation, why I would need to call that in this case.

Second, if I call `Config::restore()` to be able to use the configuration items in the way described, it will cause issues elsewhere.  For example, if we deploy our Laravel project from a CI/CD server, running the `command composer install --no-dev --optimize-autoloader -vvv`, which then runs the command `php -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='1536M' artisan package:discover --ansi` creates a significant delay as multiple timeouts occur because the CI/CD server tries to connect to the production database to retrieve the configuration items.

**Comment by klimov-paul** [comment]
Automatic item restoration from storage is covered by unit test:
https://github.com/illuminatech/config/blob/1.4.0/tests/PersistentRepositoryTest.php#L424-L470

I can not see any problem around it.

Most likely you get inconsistent behavior due to inconsistent manipulation over `Repository::$items`.
Automatic restoration performed **only once** on the first access to the key.
If you reset `Repository::$items` afterwards automatic restoration will not occur second time.

In your flow:

- You boot First ServiceProvider which swaps standard config with the persistent confit
- Some other ServiceProvider boots accesing some key from persistent confit, calling `restore()` in the process
- You boot Last ServiceProvider, which adds new items to persistent config, for these `restore()` is not invoked automatically

The possible solution is reseting `Repository::$isRestored` on `Repository::setItems()` call.

**Comment by klimov-paul** [comment]
I will make the fix.
However, even after it will be applied you will still get a problem: you program will perform 2 request to the persistent storage (e.g. database) during the configuration stage, which will affect the performance.

You need to pick more consistent way to setup persistent configuration items.

**Comment by asiral** [comment]
Thanks for this.  Do you have a recommendation for what you mean by a more consistent way?  I abbreviated for clarity in the details I provided.  But we set all configuration items through service providers.  You can just take `TestTwoServiceProvider` and create two different service providers for the two arrays of configuration items.  This is how we use the library.  All configuration items are set in service providers only, but we have many service providers setting the configuration items.

**Comment by klimov-paul** [comment]
Sorry, but I can not give you any advice, since I have no idea what you are trying to achieve but separating persistent config repository setup into 2 different service providers.

I have already put all documention at [README.md](https://github.com/illuminatech/config/blob/1.4.0/README.md).

Try to use [Illuminatech\Config\Providers\AbstractPersistentConfigServiceProvider](https://github.com/illuminatech/config/blob/1.4.0/src/Providers/AbstractPersistentConfigServiceProvider.php). May be it will help.

**Comment by asiral** [comment]
I will provide more context, even if there is no clear resolution.  But maybe it will help determine if this use case is not supported by the library or can help others experiencing the same problem.

The setup of the persistent configuration repository is not separated between two different service providers.  We have one service provider to extend the configuration repository with this package.  We follow the recommendation from the [README](https://github.com/illuminatech/config/blob/1.4.0/README.md?plain=1#L101).   The example below could or could not also set configuration items, but that would not change this use case.

```
<?php

namespace App\Providers;

use DateInterval;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\ServiceProvider;
use Illuminatech\Config\PersistentRepository;
use Illuminatech\Config\StorageEloquent;
use App\Models\ConfigurationItem;

class TestServiceProvider extends ServiceProvider
{
    protected string $configItemCacheKey = 'application.persistent.config';
    protected int|DateInterval $configItemCacheTtl = 3600 * 24;

    public function boot(): void
    {
        $this->app->extend('config', function ($originConfig) {
            $storage = new StorageEloquent(ConfigurationItem::class);
            $newConfigRepository = (new PersistentRepository($originConfig, $storage))
                ->setCache($this->app->make('cache.store'))
                ->setCacheKey($this->configItemCacheKey)
                ->setCacheTtl($this->configItemCacheTtl);

            Config::swap($newConfigRepository);

            return $newConfigRepository;
        });

    }
}
```

Most complex applications will be organized into multiple services, each with their own ServiceProvider.  An example of this would be:

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Config;
use Illuminate\Support\ServiceProvider;

class TestTwoServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $existingItems = Config::getItems()->toArray();
        $items = [
            'services.example.item1' => [
                'label' => 'Item 1',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ],
            'services.example.item2' => [
                'label' => 'Item 2',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ],
        ];
        $newItems = array_merge($existingItems, $items);
        config()->setItems($newItems);
    }
}
````

And:

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Config;
use Illuminate\Support\ServiceProvider;

class TestThreeServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $existingItems = Config::getItems()->toArray();
        $secondItems = [
            'services.example2.item1' => [
                'label' => 'Item 1 of Example 2',
                'rules' => ['required', 'array'],
                'cast' => 'array'
            ]
        ];
        $newItems = array_merge($existingItems, $secondItems);
        config()->setItems($newItems);
    }
}
````

We then have two ServiceProviders in our application.  But we want to organize the configuration items for each service within their respective code.  

I am concerned if we use `AbstractPersistentConfigServiceProvider` for multiple ServiceProviders, it will be an issue to repeatedly `extend` the configuration repository in the same way.

I hope I have at least been able to make our use case a little clearer.

**Comment by klimov-paul** [comment]
Resolved by commit 429b8d370fe3ff0db0af46c8b8c46b7def7a5587

**Comment by klimov-paul** [comment]
> The example below could or could not also set configuration items, but that would not change this use case...
   Most complex applications will be organized into multiple services, each with their own ServiceProvider. 

It seems you are missing the whole point of this package.
It is not about storing configuration value in the database instead of writing it into a file.

It is about **overriding** some default configuration written in the files via database values.

This means that if you have multiple ServiceProviders, which adjusts application configuration "on-the-fly" instead of usaging the regular configuration files (e.g. "/config/*.php"), you should setup the config override **after** them - not before.

This can be achieved via usage of dedicated DI Container key.
For example:

```php

use Illuminate\Support\ServiceProvider;
use Illuminatech\Config\Providers\AbstractPersistentConfigServiceProvider;

class FooServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->config->set('services.foo', [
             'access_key' => 'foo-access-key',
        ]);

        // prepare its share of configurable items:
        $this->app->set('persistent-config-items', [
             'services.foo.access_key' => [
                 'label' => 'Foo access key',
                 'rules' => ['string'],
             ],
        ]);
    }
}

class BarServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->config->set('services.bar', [
             'host' => 'bar-host',
        ]);

        // adds its share of configurable items to already existing one:
        $this->app->extends('persistent-config-items', function ($persistentConfigItems) { 
             return array_merge($persistentConfigItems, [
                 'services.bar.host' => [
                     'label' => 'Bar Host name',
                     'rules' => ['string'],
                 ],
            ]);
        });
    }
}

class PersistentConfigServiceProvider extends AbstractPersistentConfigServiceProvider
{
    protected function storage(): StorageContract
    {
        return (new StorageDb($this->app->make('db.connection')));
    }

    protected function items(): array
    {
        // use configurable items prepared early by other Service Providers
        return $this->app->get('persistent-config-items');
    }
}
```

**Comment by asiral** [comment]
I really appreciate this assistance.  But I am still facing significant issues I cannot get past.  I have refactored a large amount of the code in my project which has allowed me to call `setItems` only once, as described in the README, with all configuration item definitions for all my services.

However, as stated in the first message, using something like `Config::get('services.example')` _still_ returns null, but `Config::get('services.example.item1')` does not.

Now I have only one service provider, which extends the `Config` feature, and sets the persistent configuration items once in the entire code.

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Config;
use Illuminatech\Config\PersistentRepository;
use Illuminatech\Config\StorageEloquent;
use App\Models\ConfigurationItem;
use Illuminate\Support\ServiceProvider;

class ConfigServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $this->app->extend('config', function ($originConfig)  {
            $storage = new StorageEloquent(ConfigurationItem::class);
            $newConfigRepository = (new PersistentRepository($originConfig, $storage))
                ->setItems([
	                'services.example.item1' => [
		                'label' => 'Item 1',
		                'rules' => ['required', 'array'],
		                'cast' => 'array'
	                ],
	                'services.example.item2' => [
		                'label' => 'Item 2',
		                'rules' => ['required', 'array'],
		                'cast' => 'array'
	                ],
                ]);
            Config::swap($newConfigRepository);
            return $newConfigRepository;
        });
    }
}
```
Then, just declaring a route to a single action controller like below:
```
<?php

namespace App\Http\Controllers;

use Config;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController {

    public function __invoke(Request $request) {
	$config = Config::get('services.example');
	//returns null
	ddd($config);
	$config = Config::get('services.example.item1');
	//does not return null
	ddd($config);
    }
}
```
I am using v1.4.1 now.

**Comment by asiral** [comment]
Adding to your points above, even if I have a config file and load it in a Service Provider _before_ loading this package's repository, like below, the issue persists.  So, first `FooServiceProvider` is loaded followed by the `ConfigServiceProvider` above.
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class FooServiceProvider extends ServiceProvider
{
	public function register()
	{
		parent::register();
		$this->mergeConfigFrom(__DIR__ . '/../config/services.php', 'services');
	}
}
```
The `services.php` file looks like this:
```
<?php

return [
    "example" => [
        "item1" => [
            2015
        ]
    ]
];
```
And calling `Config::get('services.example')` will not return what is in the database, despite the README, unless I have failed to understand something else here.

> Then anytime you access 'config' service in your application via config() function, \Illuminate\Support\Facades\Config facade or via service container you will interact with \Illuminatech\Config\PersistentRepository instance getting values modified by database data.
